### ISSUE TITLE
uptake Scala 3.3.0

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-http#152]
follow up to #150 and https://github.com/apache/incubator-pekko/pull/270

**Comment by mdedetrich** [comment]
@pjfanning Lets use `0.0.0+4411-6fe04045-SNAPSHOT` as the pekko-http version from https://github.com/apache/incubator-pekko-http/actions/runs/5092919848/jobs/9154894284

**Comment by pjfanning** [comment]
this is done
