### ISSUE TITLE
Unshading + upgrading parboiled to 2.5.0 has exposed consumers to binary non-compatibility between parboiled 2.4.1 and 2.5.0

### ISSUE THREAD

**Issue by jphelp32** [apache/incubator-pekko-http#174]
The parboiled 2.5.0 update broke binary compatibility in the CharPredicate.apply() method. And un-shading this dependency in pekko has now exposed that to consumers. I'm wondering if there is any possibility of pushing a fix to parboiled (new version 2.5.1?) that brings back binary compatibility with 2.4.1?

**Comment by pjfanning** [comment]
@jphelp32 if you want changes to parboiled, shouldn't you report them parboiled?

**Comment by pjfanning** [comment]
There is a small overlap in Parboiled and Pekko contributors but it isn't 100%.

We can leave this open and Pekko will document the migration issue.
