### ISSUE TITLE
examine licensing impact of Tim Kientzl code/ideas

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-http#195]
https://github.com/apache/incubator-pekko-http/blob/5e82a0bc168644d5219b77877cbd337233aa3915/http-core/src/main/scala/org/apache/pekko/http/scaladsl/model/DateTime.scala#L191

* will probably need to track down the original Tim Kientzl code/ideas to see if we need to update our license and headers
* part of #35

**Comment by pjfanning** [comment]
@jrudolph @raboof would either of you know where the original code might be found?

It's unlikely to have to go this far but if we did have trouble probably licensing this code, would it be feasible to use the java.time API in the Java runtime to replace some of this code?

**Comment by jrudolph** [comment]
@sirthias do you remember where you got that from? The referenced code probably just isn't online any more...

**Comment by jrudolph** [comment]
Btw. it was introduced here in 2011: https://github.com/spray/spray/commit/86f296d0544525688b69dfde45dd789741e86be5 :)

**Comment by justinmclean** [comment]
I assume this person?? https://www.linkedin.com/in/timkientzle/

**Comment by justinmclean** [comment]
An option is to contact the person and ask them if you can use their code and license it under the Apache license.

**Comment by sirthias** [comment]
I do remember adding this code.
I think the original implementation was in C or something like that and I transcribed it.
I'll try and find the original source.

**Comment by pjfanning** [comment]
I'm pretty sure the author is @kientzle

**Comment by sirthias** [comment]
Well, it indeed looks like `spray` and `akka-http` are now the only searchable places linking this algorithm with @kientzle.
The web sure was a different place 12 years ago... (Can't believe this amount of time has passed!)
I agree that the best way forward here it likely to simply reach out to the @kientzle himself and ask for licensing details.

I'd assume that replacing the logic with something in `java.time` will have detrimental effects on performance.
At least I know that at the time there was nothing as clean, simple and fast that would allow us to convert a `System.currentTimeMillis` into a `Date` header, which needed to be in every HTTP response.
(However, I think the `Date` header caching logic came later...)

**Comment by pjfanning** [comment]
@kientzle Would you be able to give us permission to use your RFC1123 implementation under an Apache license?

**Comment by kientzle** [comment]
I have no concerns with the use here.  Enjoy!

**Comment by kientzle** [comment]
I suppose I should be a little more explicit:  You have my permission to use this implementation under an Apache license.

**Comment by jrudolph** [comment]
Thanks, Tim, for the swift reply and congrats to providing code that still proves itself useful after ~25 years.

**Comment by jrudolph** [comment]
Added a bit about that code to the LICENSE file in #205.
