### ISSUE TITLE
scaladoc links to java runtime classes are broken

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-http#216]
see https://github.com/apache/incubator-pekko-http/actions/runs/5427033437/jobs/9878610786

has issues like:
```
`[https://docs.oracle.com/en/java/javase/11/docs/api/java/util/Map.html`](https://docs.oracle.com/en/java/javase/11/docs/api/java/util/Map.html) status 404 Not Found
 - ../../../../../target/scala-2.13/unidoc/org/apache/pekko/http/javadsl/model/headers/HttpCredentials.html
 - ../../../../../target/scala-2.13/unidoc/org/apache/pekko/http/javadsl/server/AllDirectives.html
 - ... 3 more
```

should be https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Map.html

The sbt settings closely match those in incubator-pekko but the scaladoc is generating ok in incubator-pekko

**Comment by mdedetrich** [comment]
@pjfanning So I think the core issue is this https://github.com/ThoughtWorksInc/sbt-api-mappings/blob/5b1e4f11647421d287d3a26ed7fb077474ea7a3e/src/main/scala/com/thoughtworks/sbtApiMappings/BootstrapApiMappings.scala#L37-L43 although I am still getting the issue when running with JDK 11, investigating further

**Comment by mdedetrich** [comment]
Re-opening since its still broken

**Comment by pjfanning** [comment]
@mdedetrich is this safe to close? - we have the link-validator job running in CI

**Comment by mdedetrich** [comment]
Yes

**Comment by jrudolph** [comment]
No, the link validator is still broken.

**Comment by mdedetrich** [comment]
@jrudolph Huh? https://github.com/apache/incubator-pekko-http/actions/runs/5643524801

**Comment by jrudolph** [comment]
Last time it ran, it failed, and then removed its settings accidentally...

https://github.com/apache/incubator-pekko-http/actions/runs/5643524801/job/15285543470#step:8:9

```
can't read [scripts/link-validator.conf]
```

It seems to fail silently.

**Comment by mdedetrich** [comment]
Oh I see, let me rename issue so it's clearer then

**Comment by jrudolph** [comment]
This issue is probably still existing, and the other is another issue which masks this.

**Comment by mdedetrich** [comment]
> This issue is probably still existing, and the other is another issue which masks this.

I remember fixing/verifying the broken links, so unless some change was introduced which broke the links it should be fine.

**Comment by jrudolph** [comment]
:+1:
