### ISSUE TITLE
acknowledge Heiko Seeburger license

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-http#250]
ASL headers with Heiko Seeburger copyright

```
29. ./http-tests/src/test/java/org/apache/pekko/http/javadsl/marshalling/sse/EventStreamMarshallingTest.java
30. ./http-tests/src/test/java/org/apache/pekko/http/javadsl/unmarshalling/sse/EventStreamUnmarshallingTest.java
31. ./http-core/src/test/java/org/apache/pekko/http/javadsl/model/sse/ServerSentEventTest.java
32. ./http-core/src/main/java/org/apache/pekko/http/javadsl/model/sse/ServerSentEvent.java
33. ./http-core/src/main/java/org/apache/pekko/http/javadsl/model/headers/LastEventId.java
```

**Comment by pjfanning** [comment]
@jrudolph any idea where these files originate? Unfortunately, we need to track down the original files so that we can see if the project has a LICENSE or NOTICE that we need to copy too.

**Comment by pjfanning** [comment]
Could they be from https://github.com/hseeberger/akka-http-json ? The copyright matches but I'm not sure if all the files come from there.

**Comment by pjfanning** [comment]
I think this is where they are from - https://github.com/hseeberger/akka-sse

**Comment by jrudolph** [comment]
This has probably been an oversight when akka-sse has been merged in. In any case, it was @hseeberger himself who proposed the merge (in https://github.com/akka/akka-http/pull/1116), so IMO we can take it as is. Let's add a section to LICENSE to acknowledge that some code files have his copyright note on top.

**Comment by hseeberger** [comment]
We have not changed the headers? D'oh!
Of course I am cool with changing the headers in akka-http and elsewhere, no need to mention my copyright/license/anything.

**Comment by pjfanning** [comment]
> We have not changed the headers? D'oh! Of course I am cool with changing the headers in akka-http and elsewhere, no need to mention my copyright/license/anything.

Thanks @hseeberger - it's easier for us to just keep the headers as is. What we are missing is adding something to our LICENSE. I am working on that now.

Changing the headers would require a whole extra level of ASF bureaucracy.

**Comment by hseeberger** [comment]
Hehe, then my name shall not be forgotten ;-)
