### ISSUE TITLE
Update h2spec

### ISSUE THREAD

**Issue by lomigmegard** [apache/incubator-pekko-http#262]
Currently tests are using version `1.5.0`, which is from 2016. 

My current machine (Apple M1) Seg Fault on it (see https://github.com/apache/incubator-pekko-http/issues/218#issuecomment-1646844106), making the `H2SpecIntegrationSpec` test suite fail.

```
./http2-tests/target/h2spec_darwin_amd64/h2spec --dryrun
[1]    3328 segmentation fault  ./http2-tests/target/h2spec_darwin_amd64/h2spec --dryrun
```

Updating h2spec to its [latest version](https://github.com/summerwind/h2spec/releases) `2.6.0` would hopefully fix the issue. 

Note this is non-critical as the current version is working well in the CI environment.

**Comment by pjfanning** [comment]
I'm not sure if h2spec supports Mac Silicon.

There only appear to be downloads for Mac AMD64 - https://github.com/summerwind/h2spec/releases/

**Comment by lomigmegard** [comment]
Indeed, no binaries for arm64/aarch64. 

I still think this issue makes sense to eventually update to a more recent version.

**Comment by lomigmegard** [comment]
The update to 2.6.0 makes the new `h2spec` binary work on Apple Silicon, at least transparently using Rosetta (https://github.com/apache/incubator-pekko-http/issues/218#issuecomment-1648476214)

**Comment by jrudolph** [comment]
> The update to 2.6.0 makes the new `h2spec` binary work on Apple Silicon, at least transparently using Rosetta ([#218 (comment)](https://github.com/apache/incubator-pekko-http/issues/218#issuecomment-1648476214))

Great to know. I guess Rosetta hit a corner case in the old release.
