### ISSUE TITLE
remove use of lightbend sbt paradox plugin

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-http#27]
* in short term, we are likely to switch to plain sbt-paradox plugin
* until we have our own pekko plugin
* useful to get rid of Lightbend/Akka branding
* also seems that Lightbend copy of the plugin stops us adding links to other web sites (like the Akka site)

**Comment by pjfanning** [comment]
#29 merged

**Comment by jrudolph** [comment]
> also seems that Lightbend copy of the plugin stops us adding links to other web sites (like the Akka site)

That seems unlikely. Plain markdown links should work for external links. Make sure not to use the `[page]` syntax for the external ones :)
