### ISSUE TITLE
test with pekko 1.1 snapshots as well as pekko 1.0.1

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-http#293]
* We intend to keep the official dependency on pekko core as 1.0.1
  * We need to keep testing with this version to ensure pekko-http changes don't break our ability to run with pekko core 1.0.1
* We need to also test with the latest pekko 1.1 snapshots
* We may also want to test with the latest pekko 1.0 snapshots

I would suggest that the PRs are only tested with pekko 1.0.1. Maybe we only need a nightly run with latest pekko 1.1 snapshot.

**Comment by pjfanning** [comment]
@mdedetrich it looks like we are testing nightly build against pekko 1.0.1 (default) and pekko 1.0 (main)

see 'main' run that tests with Pekko 1.0.1+23-127e71a3-SNAPSHOT
https://github.com/apache/incubator-pekko-http/actions/runs/5774094249/job/15650688858

We need a test that tests with Pekko 1.1 snapshot.
There might be an argument to replace the Pekko 1.0 snapshot tests with Pekko 1.1 snapshot tests - but we can test both if that is the consensus.

**Comment by pjfanning** [comment]
@mdedetrich I think the PekkoDependency.scala regex is the issue here - that it doesn't work with '-RC0' or '-M0' versions.

It appears to only consider '1.0.1+5-abcd-SNAPSHOT' format.

```
    val snapshotVersionR = """href=".*/((\d+)\.(\d+)\.(\d+)\+(\d+)-[0-9a-f]+-SNAPSHOT)/"""".r
```

**Comment by mdedetrich** [comment]
```scala
val snapshotVersionR = """href=".*/((\d+)\.(\d+)\.(\d+)(-(M|RC)(\d+))?\+(\d+)-[0-9a-f]+-SNAPSHOT)/""""".r
```

Is an updated regex which will work (see https://regex101.com/r/ynvHsT/1), although the code with the groupings i.e. https://github.com/apache/incubator-pekko-http/blob/05bcea79de2fe37f5e687bc85facaf96742dc5c6/project/PekkoDependency.scala#L112 may need to be fixed. 

> I found this - https://github.com/G00fY2/version-compare - I haven't tested it but a small self contained lib might be a nice way to do this.

The version format is determined by sbt-dynver and they actually provide a library that provides methods which lets you query versions/snapshots etc etc, see https://github.com/sbt/sbt-dynver#library-usage so thats another option.

**Comment by pjfanning** [comment]
I agree the new regex is better but we may want something that compares RC0 as being newer than M0 - I know that alphanumerically this is already the case - but it feels like version number comparison is fairly hard and using a lib function seems like a good idea. sbt librarymanagment has VersionNumber class which might also work.

We can use the new regex as an interim solution, if you like.

**Comment by mdedetrich** [comment]
I would prefer if we do the quicker solution for now because I had the intention of replacing this code and the concept behind it entirely.

The way its currently set up means the pekko-http build is not deterministic which means it can provide surprising results. This means it's arguable not the ideal Apache way at least from the pov of building from source (this is also some of the context behind the mailing list discussion regarding milestones).

It's also brittle as has already been demonstrated, we really shouldn't have our builds be dependant on snapshots like this.

**Comment by mdedetrich** [comment]
Additionally using pinpointed milestones solves the sorting issue, makes it extremely clear what is going on which additional makes setting up testing branches for different Pekko minor versions more trivial.

Put differently, if we are spending all of this effort in getting dependencies from a repository, parsing which ones come before and which ones come after then we are just reinventing a non ideal solution to pinpointed versions.

**Comment by pjfanning** [comment]
done
