### ISSUE TITLE
Nightly builds against Pekko main are failing since August

### ISSUE THREAD

**Issue by jrudolph** [apache/incubator-pekko-http#331]
This seems to happen somewhat reliably with a problem in the protobuf-v3 snapshot jar? Or maybe somethings wrong with the name encoding?

E.g.

https://github.com/apache/incubator-pekko-http/actions/runs/5816195216/job/15768928396#step:7:404

```
Caused by: java.io.IOException: Error accessing /home/runner/.cache/coursier/v1/https/repository.apache.org/content/repositories/snapshots/org/apache/pekko/pekko-protobuf-v3_2.12/1.1.0-M0%2B25-d6ddba13-SNAPSHOT/pekko-protobuf-v3_2.12-1.1.0-M0%2B25-d6ddba13-SNAPSHOT.jar
```

**Comment by pjfanning** [comment]
@jrudolph I have https://github.com/apache/incubator-pekko/issues/685. I think we might need to patch sbt-assembly to change how it sets zip64 headers in the output jar file.

**Comment by jrudolph** [comment]
No need to create an issue, it's a JDK bug.

**Comment by mdedetrich** [comment]
> No need to create an issue, it's a JDK bug.

That may be true but its easily solvable by just not creating Zip64 encoding for files inside jar unless it's needed (which is what my PR does)

**Comment by jrudolph** [comment]
Btw. the issue in the latest nightly is this:

```
[error] Caused by: java.util.zip.ZipException: Invalid CEN header (invalid extra data field size for tag: 0x4000 at 787)
```

i.e. just a broken  extra field entry in many files.

**Comment by pjfanning** [comment]
https://github.com/apache/incubator-pekko-http/actions/runs/6594629032 passed
