### ISSUE TITLE
Question regarding to the difference between http and http/2 client API

### ISSUE THREAD

**Issue by nlpersimon** [apache/incubator-pekko-http#364]
Hi, I have a question regarding to the difference between http and http/2 client API.

From the documentation of [Host-Level Client-Side API](https://nightlies.apache.org/pekko/docs/pekko-http/1.0/docs/client-side/host-level.html#using-a-host-connection-pool), the library gives me a flow in type `[Flow[(HttpRequest, T), (Try[HttpResponse], T), HostConnectionPool]]`. To my understanding, the `Try[HttpResponse]` means that the request will not necessarily be processed by the library successfully, and I'll need to catch exceptions, which does make sense to me.

However, the documentation of [Client-Side HTTP/2](https://nightlies.apache.org/pekko/docs/pekko-http/1.0/docs/client-side/http2.html#request-response-ordering) says that the library gives me a flow in type `Flow[HttpRequest, HttpResponse, Any]`. Does that mean a request is guaranteed to obtain a response, and all the exceptions are somehow handled from the library side?

Thank you!

**Comment by pjfanning** [comment]
I think it is sensible to assume HTTP requests can fail. The sample code in those 2 doc pages use different approaches. I would suggest that you try using valid and invalid URLs when testing your code to verify that you handle failure cases.

**Comment by jrudolph** [comment]
On the HTTP/2 side, there's much less infrastructure available, in particular, there's only a connection level API, which for both HTTP/1.1 and HTTP/2 has the given signature without the extra `Try` wrapping because if anything goes wrong on the connection, the whole connection is brought down.

For the host-level (pool) API, the extra failure possibility is more a detail of the API.

**Comment by nlpersimon** [comment]
Thanks for your clarification! I had tested my application with an invalid url, and it got response with status code 502 and body "The server closed the connection before delivering a response." So it looks like if I anything goes wrong on the library side, I would just get a 502 response.

My question in this issue has been answered. Appreciate your help!
But I've another question regarding to "The HTTP/2 connection was shut down while the request was still ongoing". Should I open another issue or it is okay to continue with this issue?

**Comment by pjfanning** [comment]
It makes more sense to create an issue but please provide some code to help demo the issue. Stack trace or logging too, if you have them.
