### ISSUE TITLE
scala steward job does not work

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-http#379]
Scala Steward job is getting very confused. It thinks the PRs in https://github.com/apache/incubator-pekko (another repo) relate to this repo. It does not raise PRs for this repo as a result.

https://github.com/apache/incubator-pekko-http/actions/runs/7235045256/job/19712045431

fyi @mdedetrich 

example confusion
```
  2023-12-17 00:14:03,022 INFO  Process update org.scala-sbt:sbt : 1.9.7 -> 1.9.8
  2023-12-17 00:14:03,243 INFO  Found PR https://github.com/apache/incubator-pekko/pull/845
  2023-12-17 00:14:03,271 INFO  PR update strategy is set to always
  2023-12-17 00:14:03,271 INFO  Reset update/sbt-1.9.8 to main and apply again
  2023-12-17 00:14:05,449 INFO  Push 1 commit(s)
```

Is it possible that the secrets are actually set up only to support the incubator-pekko repo?

https://github.com/apache/incubator-pekko-http/blob/main/.github/workflows/scala-steward.yml#L15-L17

**Comment by pjfanning** [comment]
@mdedetrich could you review this?

**Comment by mdedetrich** [comment]
Upstream issue created at https://issues.apache.org/jira/browse/INFRA-25323

**Comment by mdedetrich** [comment]
Upstream issue created at https://github.com/scala-steward-org/scala-steward/issues/3257

**Comment by pjfanning** [comment]
@mdedetrich the job failed again last night. Different issue - a permissions issue with the job accessing this GitHub repo (presumably when trying to create PRs).

https://github.com/apache/incubator-pekko-http/actions/runs/7434747347/job/20229260334#step:3:291

**Comment by pjfanning** [comment]
```
  2024-01-07 00:12:58,676 INFO  Found 13 updates:
    com.dwijnand:sbt-dynver : 4.1.1 -> 5.0.1
    com.github.pjfanning:sbt-pekko-build : 0.2.0 -> 0.2.1
    com.github.sbt:sbt-license-report : 1.5.0 -> 1.6.1
    com.google.code.gson:gson : 2.9.0 -> 2.9.1
    com.lightbend.paradox:sbt-paradox : 0.9.2 -> 0.10.5
    com.lightbend.paradox:sbt-paradox-apidoc : 0.10.1 -> 1.0.0
    de.heikoseeberger:sbt-header : 5.9.0 -> 5.10.0
    org.kohsuke:github-api : 1.306 -> 1.318
    org.parboiled:(parboiled, parboiled_2.12, parboiled_2.13, parboiled_3) : 2.5.0 -> 2.5.1
    org.scala-sbt:sbt : 1.9.7 -> 1.9.8
    org.scalameta:sbt-scalafmt : 2.4.6 -> 2.5.2
    org.scalameta:(scalafmt-core, scalafmt-core_2.13) : 3.7.11 -> 3.7.17
    pl.project13.scala:sbt-jmh : 0.4.3 -> 0.4.7
```

**Comment by mdedetrich** [comment]
Yes I know, the core INFRA ticket has already been updated with relevant info

**Comment by mdedetrich** [comment]
@pjfanning With the permission issue fixed scala steward is now working (see https://github.com/apache/incubator-pekko-http/actions/runs/7434747347/job/20243280422 and as an example PR https://github.com/apache/incubator-pekko-http/pull/399)

Closing ticket
