### ISSUE TITLE
Upstream former DynamicRuleDispatch.lookup optimization to parboiled2

### ISSUE THREAD

**Issue by jrudolph** [apache/incubator-pekko-http#45]
Because we will likely remove that optimization in #14 by going back to upstream parboiled2.

**Comment by mdedetrich** [comment]
@jrudolph Do you want to work on this? I was thinking of having a look at it by end of week since it makes sense to upstream sooner rather than later (upstream changes take time to review)

**Comment by mdedetrich** [comment]
We could but I am not entirely sure its necessary, the performance improvements don't seem to be that controversial or large in scope and it might be almost as fast just to create a PR.

**Comment by mdedetrich** [comment]
> We shouldn't tackle that right now. It's a nice to have but not strictly required right now.

If the reason behind not tackling it right now is due to prioritisation then thats fair
