### ISSUE TITLE
Add doc generation check to CI

### ISSUE THREAD

**Issue by mdedetrich** [apache/incubator-pekko-http#504]
See https://github.com/apache/incubator-pekko-http/pull/503 for why, a regression was made in latest Scala 2.13.13 version which broke doc generation. Should have a CI check like the one that was added in pekko core so that we know if something breaks doc generation when a PR is made

**Comment by pjfanning** [comment]
This is my bad - I merged https://github.com/apache/incubator-pekko-http/actions/runs/8065545436/job/22031571657 despite the broken link-validator check. I'm just so used to the link validations failing for random http(s) issues that I dodn't check and see that the genjavadoc issue happened in this run.
