### ISSUE TITLE
docs: issue with scala/java links

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-http#68]
In some `.md` files, we have links like:

*introduction.md*
```
See @scala[@ref[JSON Support](common/json-support.md))]@java[@ref[JSON Support](common/json-support.md#jackson-support))] for more information about integration
```

This is being rendered as 2 links with the same name beside each other, when I think the intent is that one shows depending on whether you've chosen Java or Scala.

See https://nightlies.apache.org/pekko/docs/pekko-http/main-snapshot/docs//introduction.html

<img width="704" alt="image" src="https://user-images.githubusercontent.com/11783444/219621596-49a1b927-ebe8-4c98-afb3-095a7dbdb31e.png">

This is just one example. I checked a few more and they have similar issues.

**Comment by pjfanning** [comment]
@jrudolph @mdedetrich small rendering issue in pekko-http docs

**Comment by mdedetrich** [comment]
There was some rendering issues which I noticed were in the original Akka version as well when doing the package rename, was going to fix them in a future PR because I wanted to separate the concerns.

Thanks for making an issue on this.

**Comment by jrudolph** [comment]
There are probably a few things like that which need to be fixed in the theme.

**Comment by jrudolph** [comment]
Probably caused by https://github.com/apache/incubator-pekko-sbt-paradox/issues/25

**Comment by pjfanning** [comment]
A possibly separate issue is that in introduction.md, the instructions for using `sbt new akka/akka-http-quickstart-java.g8` are not appearing. Only the Scala tab shows - see https://nightlies.apache.org/pekko/docs/pekko-http/main-snapshot/docs/introduction.html

**Comment by jrudolph** [comment]
> A possibly separate issue is that in introduction.md, the instructions for using `sbt new akka/akka-http-quickstart-java.g8` are not appearing.

I think this is "as designed". You need to use the switcher on the nav bar to switch to Java and you will get the other instructions. AFAIK only source snippets (`@@snip`) allow "real tabs" that are always shown but not the `@@@ div { .group-scala }` style of creating tabs.

**Comment by pjfanning** [comment]
this is fixed
