### ISSUE TITLE
Regenerate images in documentation which have akka references

### ISSUE THREAD

**Issue by mdedetrich** [apache/incubator-pekko-http#99]
Can't remember precisely where but there are images in the current pekko Paradox docs which refer to Akka. Some examples I can remember are a visalized flamegraph and also a screenshot of a http webserver that still has Akka in it.

We should regenerate the screenshots so that they have Pekko naming instead and update the docs to reflect this.

**Comment by jrudolph** [comment]
E.g. here but unlikely to be reproducible:

https://nightlies.apache.org/pekko/docs/pekko-http/main-snapshot/docs/handling-blocking-operations-in-pekko-http-routes.html

**Comment by mdedetrich** [comment]
> E.g. here but unlikely to be reproducible:
> 
> https://nightlies.apache.org/pekko/docs/pekko-http/main-snapshot/docs/handling-blocking-operations-in-pekko-http-routes.html

For cases like this we could just probably blur the akka?

**Comment by jrudolph** [comment]
I guess I would mostly just ignore it for now.

**Comment by mdedetrich** [comment]
> I guess I would mostly just ignore it for now.

I did a very quick search and there isn't even an Akka trademark that is actually associated with the project so I think its quite safe to ignore and if someone complains (plus its valid) we can just blur it
